"""Validation and generation of editable strategic LevelBuild sources."""

from pathlib import Path
from PIL import Image


REQUIRED_TEXTURES = {
    'Div_map.webp': 'RGB',
    'HeightMap.png': 'I;16',
    'Minimap.webp': 'RGB',
    'Overview.webp': ('RGB', 'RGBA'),
    'Preview.webp': 'RGB',
    'sdb.png': 'RGB',
    'Splat_map.png': 'RGB',
    'WaterFlow.png': 'RGB',
}


def validate_levelbuild_source(source):
    root = Path(source).resolve()
    if not root.is_dir():
        raise ValueError('LevelBuild source directory is missing')
    for name in ('Map.ndf', 'GraphicSettings.ndf'):
        path = root / name
        if not path.is_file() or not path.read_bytes().strip():
            raise ValueError(f'Missing or empty LevelBuild source: {name}')
    dimensions = None
    for name, mode in REQUIRED_TEXTURES.items():
        path = root / name
        if not path.is_file():
            raise ValueError(f'Missing LevelBuild texture: {name}')
        try:
            with Image.open(path) as image:
                image.load()
                actual_mode = image.mode
                size = image.size
                actual_format = image.format
        except Exception as error:
            raise ValueError(f'Invalid LevelBuild texture: {name}') from error
        expected_format = 'WEBP' if path.suffix.lower() == '.webp' else 'PNG'
        if actual_format != expected_format:
            raise ValueError(f'{name} must use {expected_format} encoding')
        if mode == 'I;16':
            if actual_mode not in ('I;16', 'I;16B', 'I;16L'):
                raise ValueError(f'{name} must use 16-bit grayscale pixels')
        elif isinstance(mode, tuple) and actual_mode not in mode:
            raise ValueError(f'{name} must use one of {mode} pixel modes')
        elif isinstance(mode, str) and actual_mode != mode:
            raise ValueError(f'{name} must use {mode} pixels')
        if dimensions is None:
            dimensions = size
        if size != dimensions:
            raise ValueError('LevelBuild textures must have matching dimensions')
        if name == 'sdb.png' and image.getpixel((0, 0)) == (255, 0, 255):
            raise ValueError('sdb.png contains placeholder magenta surface')
        if name == 'Splat_map.png' and image.getextrema() == ((0, 0), (0, 0), (0, 0)):
            raise ValueError('Splat_map.png contains an empty terrain mask')
    return {'source': str(root), 'texture_size': list(dimensions),
            'textures': sorted(REQUIRED_TEXTURES)}


def write_blank_levelbuild_source(destination, *, map_name, render_cases_x=2,
                                  render_cases_y=2, texture_size=512):
    """Write deterministic flat terrain inputs; render cases are not strategic cells."""
    root = Path(destination).resolve()
    if not isinstance(map_name, str) or not map_name.isidentifier():
        raise ValueError('map_name must be an identifier')
    if render_cases_x <= 0 or render_cases_y <= 0 or texture_size <= 0:
        raise ValueError('render cases and texture size must be positive')
    root.mkdir(parents=True, exist_ok=True)
    surface = Image.new('RGB', (texture_size, texture_size), (78, 108, 60))
    height = Image.new('I;16', (texture_size, texture_size))
    height_pixels = height.load()
    for y in range(texture_size):
        for x in range(texture_size):
            height_pixels[x, y] = 0
    images = {
        'Div_map.webp': surface,
        'HeightMap.png': height,
        'Minimap.webp': surface.copy(),
        'Overview.webp': surface.convert('RGBA'),
        'Preview.webp': surface.copy(),
        'sdb.png': surface.copy(),
        'Splat_map.png': Image.new('RGB', (texture_size, texture_size), (255, 0, 0)),
        'WaterFlow.png': Image.new('RGB', (texture_size, texture_size), (128, 128, 128)),
    }
    for name, image in images.items():
        options = {'lossless': True} if name.endswith('.webp') else {}
        image.save(root / name, **options)
    (root / 'Map.ndf').write_text(
        "// Generated by WARNO Army General Framework\n"
        f"MapName is '{map_name}'\nMapJuncture is Juncture/Strategic\n"
        "MaxAltitudeInLBU is 2.3255813121795654\n"
        "WaterHeightInLBU is 23.255813598632812\nMapDecorSets is []\n"
        f"NbCaseX is {render_cases_x}\nNbCaseY is {render_cases_y}\n", encoding='utf-8')
    (root / 'GraphicSettings.ndf').write_text(
        "// Generated by WARNO Army General Framework\n"
        "export GraphicSettings is TPerMapGraphicSettings\n"
        "(\n"
        "    GrassParameters = $/GraphicSettings/Grass/GrassParameters_Fulda\n"
        "    BricoGrass = $/GraphicSettings/BricoGrass/Fulda\n"
        "    SplattingConfig = $/GraphicSettings/Splatting/Strategic\n"
        "    WaterParameters = $/GraphicSettings/Water/mer\n"
        "    RockParameters = $/GraphicSettings/Rock/RockFulda\n"
        "    SoundMapConfig = $/SoundMapConfig/SoundMapConfig_War_Room\n"
        "    DefaultEnvironmentSettings = $/GraphicSettings/EnvironmentSettings/Strat_2\n"
        ")\n", encoding='utf-8')
    return validate_levelbuild_source(root)
