schema: 1
deployments:
- id: dep_us_seal_belbek
  battalion: us_seal_belbek
  side: nato
  position:
  - 851500
  - 513500
  fatigue: 1
  action_points: 12
  frozen_turns: 0
  initial_losses:
    max_percent: 10
- id: dep_usmc_1st_landing
  battalion: usmc_1st_landing
  side: nato
  position:
  - 838500
  - 526500
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_usmc_2nd_landing
  battalion: usmc_2nd_landing
  side: nato
  position:
  - 851500
  - 539500
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_usmc_recon
  battalion: usmc_recon
  side: nato
  position:
  - 851500
  - 526500
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_kacha_territorial
  battalion: sov_kacha_territorial
  side: pact
  position:
  - 890500
  - 539500
  fatigue: 1
  action_points: 7
  frozen_turns: 0
- id: dep_sov_belbek_guard
  battalion: sov_belbek_guard
  side: pact
  position:
  - 903500
  - 448500
  fatigue: 0
  action_points: 8
  frozen_turns: 0
- id: dep_sov_880
  battalion: sov_880
  side: pact
  position:
  - 890500
  - 500500
  fatigue: 2
  action_points: 11
  frozen_turns: 0
  initial_losses:
    max_percent: 25
- id: dep_sov_882
  battalion: sov_882
  side: pact
  position:
  - 1085500
  - 487500
  fatigue: 0
  action_points: 11
  frozen_turns: 0
- id: dep_sov_881
  battalion: sov_881
  side: pact
  position:
  - 890500
  - 422500
  fatigue: 0
  action_points: 11
  frozen_turns: 0
- id: dep_sov_888
  battalion: sov_888
  side: pact
  position:
  - 903500
  - 383500
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_113
  battalion: sov_113
  side: pact
  position:
  - 838500
  - 331500
  fatigue: 0
  action_points: 10
  frozen_turns: 0
- id: dep_sov_1613
  battalion: sov_1613
  side: pact
  position:
  - 851500
  - 331500
  fatigue: 0
  action_points: 5
  frozen_turns: 0
- id: dep_sov_1616
  battalion: sov_1616
  side: pact
  position:
  - 1098500
  - 500500
  fatigue: 0
  action_points: 5
  frozen_turns: 0
- id: dep_sov_saki_guard_v5
  battalion: sov_saki_guard_v5
  side: pact
  position:
  - 877500
  - 864500
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_simf_guard
  battalion: sov_simf_guard
  side: pact
  position:
  - 1228500
  - 695500
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_sev_guard_1
  battalion: sov_sev_guard_1
  side: pact
  position:
  - 877500.0
  - 383500.0
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_sev_guard_2
  battalion: sov_sev_guard_2
  side: pact
  position:
  - 916500.0
  - 357500.0
  fatigue: 0
  action_points: 10
  frozen_turns: 3
- id: dep_sov_810_hq
  battalion: sov_810_hq
  side: pact
  position:
  - 838500
  - 318500
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_60_pvo
  battalion: sov_60_pvo
  side: pact
  position:
  - 851500.0
  - 318500.0
  fatigue: 0
  action_points: 4
  frozen_turns: 0
- id: dep_sov_simf_at
  battalion: sov_simf_at
  side: pact
  position:
  - 1267500.0
  - 695500.0
  fatigue: 0
  action_points: 10
  frozen_turns: 2
