schema: 1
deployments:
- id: dep_us_seal_belbek
  battalion: us_seal_belbek
  side: nato
  position:
  - 851500
  - 797220
  fatigue: 1
  action_points: 12
  frozen_turns: 0
  initial_losses:
    max_percent: 10
- id: dep_usmc_1st_landing
  battalion: usmc_1st_landing
  side: nato
  position:
  - 864500
  - 745220
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_usmc_2nd_landing
  battalion: usmc_2nd_landing
  side: nato
  position:
  - 851500
  - 771220
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_usmc_recon
  battalion: usmc_recon
  side: nato
  position:
  - 851500
  - 784220
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_kacha_territorial
  battalion: sov_kacha_territorial
  side: pact
  position:
  - 890500
  - 771220
  fatigue: 1
  action_points: 7
  frozen_turns: 0
- id: dep_sov_belbek_guard
  battalion: sov_belbek_guard
  side: pact
  position:
  - 903500
  - 862220
  fatigue: 0
  action_points: 8
  frozen_turns: 0
- id: dep_sov_880
  battalion: sov_880
  side: pact
  position:
  - 890500
  - 810220
  fatigue: 2
  action_points: 11
  frozen_turns: 0
  initial_losses:
    max_percent: 25
- id: dep_sov_882
  battalion: sov_882
  side: pact
  position:
  - 1085500
  - 823220
  fatigue: 0
  action_points: 11
  frozen_turns: 0
- id: dep_sov_881
  battalion: sov_881
  side: pact
  position:
  - 890500
  - 888220
  fatigue: 0
  action_points: 11
  frozen_turns: 0
- id: dep_sov_888
  battalion: sov_888
  side: pact
  position:
  - 903500
  - 927220
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_113
  battalion: sov_113
  side: pact
  position:
  - 838500
  - 979220
  fatigue: 0
  action_points: 10
  frozen_turns: 0
- id: dep_sov_1613
  battalion: sov_1613
  side: pact
  position:
  - 851500
  - 979220
  fatigue: 0
  action_points: 5
  frozen_turns: 0
- id: dep_sov_1616
  battalion: sov_1616
  side: pact
  position:
  - 1098500
  - 810220
  fatigue: 0
  action_points: 5
  frozen_turns: 0
- id: dep_sov_saki_guard_v5
  battalion: sov_saki_guard_v5
  side: pact
  position:
  - 877500
  - 446220
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_simf_guard
  battalion: sov_simf_guard
  side: pact
  position:
  - 1228500
  - 615220
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_sev_guard_1
  battalion: sov_sev_guard_1
  side: pact
  position:
  - 877500.0
  - 927220.0
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_sov_sev_guard_2
  battalion: sov_sev_guard_2
  side: pact
  position:
  - 916500.0
  - 953220.0
  fatigue: 0
  action_points: 10
  frozen_turns: 3
- id: dep_sov_810_hq
  battalion: sov_810_hq
  side: pact
  position:
  - 838500
  - 992220
  fatigue: 0
  action_points: 12
  frozen_turns: 0
- id: dep_sov_60_pvo
  battalion: sov_60_pvo
  side: pact
  position:
  - 851500.0
  - 992220.0
  fatigue: 0
  action_points: 4
  frozen_turns: 0
- id: dep_sov_simf_at
  battalion: sov_simf_at
  side: pact
  position:
  - 1267500.0
  - 615220.0
  fatigue: 0
  action_points: 10
  frozen_turns: 2
- id: dep_usmc_beachhead_guard
  battalion: usmc_beachhead_guard
  side: nato
  position:
  - 838500
  - 784220
  fatigue: 0
  action_points: 12
  frozen_turns: 5
